[project]
name = "insta-automate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ordered-set>=4.1.0",
    "psycopg2>=2.9.10",
    "rich>=13.9.4",
    "send2trash>=1.8.3",
    "sqlalchemy>=2.0.38",
    "uiautomator2>=3.2.8",
    "xxhash>=3.5.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "pandas>=2.2.3",
]
